### ISSUE TITLE
Feature request: Callback on crash to log extra information.

### ISSUE THREAD

**Issue by daid** [jrfonseca/drmingw#30]
First off, THANKS. DrMingw and especially the "exchndl" part that you can link to your application is a great help.

I was wondering if it's possible to add the functionality to get a callback when an a fatal exception happens, and then allow the application to log some additional information. I know there is the added risk of that code throwing an exception again, not sure what would happen then.

(I have the case where a crash happens inside some of my UI handling code, and I know the type of UI control that is clicked that is causing the crash, but due to the use of function pointers the exact control is hard to trace down. If I could log the mouse position on exception, which is accessible trough a global variable in my code then I would know where the user had clicked. Which is of great assistance in finding the offending code)

I wouldn't mind building&contributing this feature. But I'm not a 100% sure where to start and if you would like this feature as well.

**Comment by jrfonseca** [comment]
I rather not maintain a complicated interface around ExcHndl.

What I could consider is exposing what's currently under `src/common` to 3rd parties, as a _debug engine_ (similar to https://msdn.microsoft.com/en-us/library/bb145126.aspx ).

If you look at https://github.com/jrfonseca/drmingw/blob/master/src/exchndl/exchndl.cpp you'll see that ExcHndl is nothing but a thin veil around the engine the code in `src/common`.  This is why I see little merit building a complex interface for ExcHndl.

Of course, `src/common.cpp` is not ready for 3rd party.  Step 0 would be clean the interface to be concise and generic, and step 1 would be to expose it as a DLL instead of static library.
