### ISSUE TITLE
ExcHndl doesn't work on Windows 10

### ISSUE THREAD

**Issue by abelharisov** [jrfonseca/drmingw#36]
Hello!
I use ExcHndl for crash reporting. It works fine on Windows 7. But on Windows 10 it doesn't write crashlogs. After some research I found out that WinApi function SetUnhandledExceptionFilter used in ExcHndl doesn't work on Windows 10 as expected. It sets exception handler, but it never called.
Do you know, how to fix this problem?

Thank you!

**Comment by jrfonseca** [comment]
I just ran the sample and tests on Windows 10 and they seem to work fine -- `SetUnhandledExceptionFilter` gets called.

Try building and running the sample that comes with DrMingw.  See whether a `sample.RPT` gets called or not.

One limitation of ExcHndl is that it only sets the unhandled exception filter on one thread.  Perhaps your app is multi-threaded and the exception is happening on a different thread?

**Comment by jrfonseca** [comment]
Also note that exceptions inside WindowProc never get caught. See the remarks at the bottom of https://msdn.microsoft.com/en-us/library/windows/desktop/ms633573.aspx

**Comment by abelharisov** [comment]
Thanks. I'll try check example later
Yes, my app is multi-threaded. But on Windows 7 crash reporting works fine. Also I use hack like (this)[http://www.debuginfo.com/articles/debugfilters.html#enforce]. Maybe technique described there not applicable on Windows 10

**Comment by jrfonseca** [comment]
Yes, I know first hand how trying to intercept Windows APIs is a tricky business.  You can see in https://github.com/apitrace/apitrace/tree/master/inject all sort of tricks I had to do in another project of mine.

Another (and probably more portable) approach would be for your application to have a `__try { .. } __except {...}` as early as a possible (preferably in the main), and then call ExcHndl somehow.  But again, this will only be practical for single thread apps.

If you're still convinced there's a bug in ExcHndl and  can provide a small test case showing the issue, please reopen this issue I'll try to look into.  Until then I'll presume the the issue is elsewhere.
