### ISSUE TITLE
mgwhelp.dll not providing any symbols

### ISSUE THREAD

**Issue by CyberShadow** [jrfonseca/drmingw#4]
Hi,

I've tried to use mgwhelp.dll as a drop-in replacement for [Very Sleepy](https://github.com/VerySleepy/verysleepy). Currently we use Wine's DbgHelp which is occasionally buggy, not very portable, uses its own DWARF parser, and doesn't understand DWARF-4.

However, I couldn't get any symbols out of it at all. I've tried with 32-bit Cygwin and MSys64 with `-gdwarf-2`, which Wine's DbgHelp manages.

**Comment by jrfonseca** [comment]
I'm not sure if mgwhelp.dll intercepts all the entrypoints that Very Sleepy uses.

To be perfectly clear, mgwhelp.dll exports all symbols, but some are straight jumps to dbghelp.dll

How exacly did you integrate mgwhelp.dll with Very Sleepy?

**Comment by CyberShadow** [comment]
Well, I simply made it load mgwhelp.dll instead of Wine's dbghelp.dll.

Here are the functions Very Sleepy uses:

https://github.com/VerySleepy/verysleepy/blob/master/src/utils/dbginterface.h

**Comment by jrfonseca** [comment]
Thanks. You can see the functions MgwHelp handles in https://github.com/jrfonseca/drmingw/blob/master/src/mgwhelp32.def

But many funtions (e.g. StackWalk64)  don't deal with symbols so passing-trhough is fine

I think the problem is fundamentally that Very Sleepy uses the Unicode functions, where as MgwHelp only intercepts the ASCIII functions.

I suspect that if we implement 

* SymFromAddrW
* SymGetLineFromAddrW64
* SymInitializeW

by using their ASCII counterparts as starting point, then things might start working.

**Comment by jrfonseca** [comment]
I only work on DrMingw in spare time, and there's not much of that lately, so I'm afraid I can't give any ETA.

@CyberShadow, by any chance, is implementing the Unicode entry-points mentioned above something you could help with?

**Comment by CyberShadow** [comment]
I am still unable to build this project.

Which exact version of MSYS and MinGW are needed? There are dozens of implementations/distributions of the above for Windows.

**Comment by jrfonseca** [comment]
> Which exact version of MSYS and MinGW are needed? There are dozens of implementations/distributions of the above for Windows.

No MSYS needed.  MinGW-W64 is needed.  I updated BUILD.md with URLs to make it crystal clear -- 
https://github.com/jrfonseca/drmingw/commit/138ab9d5f5ff2eb7d479047103b8aa982585c61b

**Comment by CyberShadow** [comment]
MinGW-W64 does not come with a make program, thus I can't use the Makefile that CMake generates.

**Comment by CyberShadow** [comment]
Can you clarify which MinGW-W64 flavor, in particular? The project provides multiple Windows downloads, and even then the installer provides multiple options as to which flavor to install. (POSIX/native threads, sjlj/SEH exception handling, ...)

**Comment by jrfonseca** [comment]
Any MinGW-W64 flavour should work. Thought a native mingw make (any ) is indeed necessary.

The thing is I always build with cross-compilers. I once built with native mingw-w64 and updated the instructions, but indeed mingw-w64 website nowadays is quite confusing regarding binaries/downloads.

I'm now attempting to build with native mingw from scratch, and will update the instructions.

**Comment by jrfonseca** [comment]
> I'm now attempting to build with native mingw from scratch, and will update the instructions.

Done. @CyberShadow , see https://github.com/jrfonseca/drmingw/blob/master/BUILD.md#native-toolchain

**Comment by CyberShadow** [comment]
Ahh, thanks. Wasn't aware of `mingw32-make`. It works now.

I'm going to attempt a 64-bit build as well (as the situation is more dire with 64 bits with Very Sleepy). Will let you know.

**Comment by CyberShadow** [comment]
Yep, worked with the same MinGW version but s/x32/x64/ s/dwarf/seh/ :

http://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.1/64-bit/threads-win32/seh/x64-4.8.1-release-win32-seh-rev5.7z/download

**Comment by jrfonseca** [comment]
The stack overflow happens on `downward-debug.exe` offset 0x218b7, but using DrMingw's `addr2line.exe` like

    addr2line.exe downward-debug.exe 0x218b7        

works fine.  In other words, the bug only happens when `mgwhelp.dll` is used inside `sleepy.exe`.

It turns out (looking at the output of `dumpbin`) that `sleepy.exe` only has 1 MB stack. And if I modify `sleepy.exe` to have a bigger stack, using `editbin` like

    editbin /stack:8388608 sleepy.exe

VerySleepy also works fine.

Maybe `mgwhelp.dll` implementation is a big stack hungry.  After all `search_func` was based from elftoolchain from Linux, and Linux has a 8MB stack by default unlike the Windows 1MB default. Not sure how easy to improve this.

On the other hand, trying to make do with 1MB stack, on a 64-bit process, and when computers come with 4GB/8GB standard, is a tad cheap ;-)   I'd suggest bumping the verysleep stack to something larger, as a temporary workaround if nothing else.

For reference, MinGW's executables appear to use a 2MB stack by default, which was why I didn't spot the issue with DrMingw's `addr2line.exe`.
