### ISSUE TITLE
Error installing 0.9.3 64bit on win7

### ISSUE THREAD

**Issue by dinkc64** [jrfonseca/drmingw#55]
Hi, I've been DrMingW for years, it's one of my favorite & most useful utilities besides the c compiler itself! :)
Starting with 0.9.3 there is an issue when I run drmingw -i, this error shows up:
![drmingw093](https://user-images.githubusercontent.com/12570148/116603819-5fa77600-a8fb-11eb-96de-dea2aa41e31c.png)

0.9.2 and all previous versions install perfectly.
I'm using Win7 w/all the latest updates.

best regards,
- dink

**Comment by jrfonseca** [comment]
The problem is are the `dbghelp.dll` `dbgcore.dll` and `symsrv.dll` redistributable Microsoft binaries.  I get these from AppVeyor/GitHub images, and it seems the latest versions are too new for Win7.

I'll try to fix this.

In the meanwhile, you can just copy theses DLLs from the older 0.9.2, and replace the ones on 0.9.3.

**Comment by jrfonseca** [comment]
Oh, almost forgot: I'm glad to hear you find it useful! :)

**Comment by alvinhochun** [comment]
Judging from a [Chrimium issue of the same problem](https://bugs.chromium.org/p/chromium/issues/detail?id=1021650), I would guess that the linked commit 7f8a701 switching to the 10.0.18362.1 version of dbghelp.dll will not actually fix this. You may need to either go earlier than that, or also ship `api-ms-win-downlevel-kernel32-l2-1-0.dll` that also comes with Debugging Tools 10.0.19041.685.

**Comment by jrfonseca** [comment]
A year passed, so my memory is faded, but I believe I actually tested on a Windows 7 VM before commit 7f8a701861f4aaf4c58250308bb99c5717ac1876.

I just re-checked, and at very least the `api-ms-win-downlevel-kernel32-l2-1-0.dll` is not listed as dependency of the dbghelp DLLs currently used.

It sounds from https://bugs.chromium.org/p/chromium/issues/detail?id=976161 there are indeed problems with 10.0.18362.1, but affect `dbgeng.dll` which we don't use in DrMingw.

So I'll assume DrMingw works until concrete evidence otherwise.

That said, sooner or later DrMingw should upgrade to SDK 10.0.19041.0 (which appears fixes the issue).
