### ISSUE TITLE
Reason for erroring out with posix threads?

### ISSUE THREAD

**Issue by alvinhochun** [jrfonseca/drmingw#61]
I see that https://github.com/jrfonseca/drmingw/commit/f3ff9b5fcfd88ea43754c48f391f8d796f15bc43 added an error when the toolchain uses posix threads. What is the reasoning behind this?

**Comment by jrfonseca** [comment]
I don't want DrMinGW accidentally built with posix threads.  At very least, posix threads would add one extra DLL dependency, a dependency that would need to be documented and redistributed, and I don't want that.

I'll add a comment to this effect.  

As general rule, there are many ways one could try to build DrMinGW (with MSVC, Cygwin, MSYS, etc), but since DrMingw is distributed primarily as executable binaries.  These create different challenges.  So I prefer to have only one method to build allowed/supported.

**Comment by alvinhochun** [comment]
I see. We build DrMingw with Krita for getting crash backtraces using `exchndl.dll`, so we ship all runtime DLLs anyway and this is not a problem for us. It would be nice if this check can be ignored by an option.
