### ISSUE TITLE
Version 0.7.0 produce empty output

### ISSUE THREAD

**Issue by dismine** [jrfonseca/drmingw#8]
Hello,

I downloaded and tried last version 0.7.0 and it seems do not works. I used exchndl.dll. All what i see in report is:
>-------------------
>
>Error occured on понедельник, апреля 27, 2015 at 12:55:39.
>
>   

I test with my example program and one i have found in folder 'sample'. Result the same. 

Previous versions 0.6.6 and 0.6.4 generate report as expected.

**Comment by jrfonseca** [comment]
That's disappointing. I added a test precisely for that.

Furthermore it works fine here (Windows 7 SP1).

Please confirm:
- Windows version and architecture
- 32bits or 64bits binaries
- if you also copied `dbghelp.dll` and `symsrv.dll` into the sample dir.

**Comment by dismine** [comment]
* I downloaded drmingw-0.7.0-win32.zip. 
* Windows XP in VirtualBox.
* I used all 5 files: dbghelp.dll, exchndl.dll, mgwhelp.dll, symsrv.dll, symsrv.yes.

**Comment by jrfonseca** [comment]
> Windows XP

OK. I'm pretty sure this is why I couldn't repro. I'm probably using some Win32 function that's not supported on Windows XP.

It's probably causing exchnld to crash inside the exception handler which is why it silently fails (to avoid infinite recursion)

I don't have a XP VM readily available, so it will take me a while to repro.

Are you confortable/willing to build drmingw from source? It's not difficult, just follow https://github.com/jrfonseca/drmingw/blob/master/BUILD.md and after it's built run

    cmake --build build --target test

to run the tests.

**Comment by dismine** [comment]
Sorry, i can't build 0.7.0.

>CMake Error at C:/Program Files/CMake/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
  least version "2.7")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.0/Modules/FindPythonInterp.cmake:153 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  tests/CMakeLists.txt:77 (find_package)

>-- Could NOT find WinDbg (missing:  WINDBG_DIR) 

But still can build 0.6.6.

**Comment by jrfonseca** [comment]
> Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
least version "2.7")

With commit c73961d2e3f24dbfe44a417ac80f79758367903f  Python should be optional.

And this issue should be fixed with 5ff4d8d843f6d7ec6424aad75f19528ad959e12b.

Thanks for reporting this.
