### ISSUE TITLE
libwinpthread-1.dll missing from release

### ISSUE THREAD

**Issue by wodim** [jrfonseca/drmingw#82]
I downloaded drmingw-0.9.8-win64.7z and libwinpthread-1.dll was missing so it wouldn't run. I downloaded a copy from [here](https://packages.msys2.org/package/mingw-w64-x86_64-libwinpthread) but you might want to include it in the release archive.

**Comment by jrfonseca** [comment]
The `libwinpthread-1.dll`  dependency is unintentional.  DrMingw should either not depend on it (ie, use Win32 threads as opposed to Posix threads) or statically link `libwinpthread-1.dll`.

It happened between 0.9.7 and 0.9.8, likely due to the new MinGW compiler toolchain from d9a82b4ac764490d83b08e946338d89d1dc1a965. 

I'll need to figure a solution, and add logic to prevent this from silently happening again.

**Comment by jrfonseca** [comment]
Going through git history, I'm starting to recollect: 3450a15f8a5e967f5061ad80433be84c38ace9f2 _should_ have ensured winpthreads are statically linked...

**Comment by alvinhochun** [comment]
Also worth noting that, when compiling with the llvm-mingw toolchain, it uses libc++ instead of libstdc++. The winpthread library is available in the toolchain, but libc++ does not actually use winpthreads.

**Comment by alvinhochun** [comment]
If you would like to to stick to GCC, mingw-builds still provides toolchains without posix threads: https://github.com/niXman/mingw-builds-binaries/releases

**Comment by jrfonseca** [comment]
Thanks @alvinhochun 

I'm building with LLVM/Clang for Arm, but still building with GCC for x86.

The odd thing here is that when I build locally `libwinpthread-1.dll` is statically linked.  I need to dig further..

**Comment by jrfonseca** [comment]
After a few experiments, I've narrowed down the issue.  It only happens on Release builds (only used for producing the binaries), and never on the Debug builds (used for continuous testing and integration.)  Why, I haven't yet figured out.  I need to reproduce locally first.

**Comment by jrfonseca** [comment]
Fixed in https://github.com/jrfonseca/drmingw/releases/tag/0.9.9

**Comment by yuansunliang1988** [comment]
> 已修复https://github.com/jrfonseca/drmingw/releases/tag/0.9.9

Can you give me the complete process of how to build and compile a drmingw program?
I used mingw to compile it and found that it reports errors：

CMake Error at CMakeLists.txt:66 (message):
  Win32 threads required.
  
Including what compiler should be used, for now I'm porting it inside my own project first, because the project with mingw64 can't generate pdb symbol files. I think it would also be helpful to analyze the problem if I can print out the stack of the crash at that time

**Comment by jrfonseca** [comment]
> Can you give me the complete process of how to build and compile a drmingw program?

If you want to build DrMingw yourself, you can follow the steps in the GitHub Action:
- https://github.com/jrfonseca/drmingw/blob/master/.github/workflows/build.yml#L31
- https://github.com/jrfonseca/drmingw/blob/master/ci/build.ps1
